repos:
-   repo: local
    hooks:
    -   id: uv-lock
        name: uv lock
        description: 'Lock dependencies with uv lock'
        entry: uv lock
        language: system
        pass_filenames: false
        always_run: true
        files: ^pyproject\.toml$
