coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
comment:
  layout: "condensed_header, reach, diff, condensed_files, condensed_footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
